set(CMAKE_BUILD_TYPE DEBUG CACHE STRING "")
set(LLVM_ENABLE_PROJECTS
  clang CACHE STRING "")
set(CLANG_BUILD_EXAMPLES OFF CACHE BOOL "")
set(LLVM_BUILD_TESTS OFF CACHE BOOL "")
set(LLVM_BUILD_TOOLS OFF CACHE BOOL "")
set(LLVM_OPTIMIZED_TABLEGEN ON CACHE BOOL "")
set(LLVM_CCACHE_BUILD ON CACHE BOOL "")
set(LLVM_PARALLEL_COMPILE_JOBS 7 CACHE STRING "")
set(LLVM_PARALLEL_LINK_JOBS 2 CACHE STRING "")
set(LLVM_ENABLE_LLD ON CACHE BOOL "")
set(LLVM_USE_SPLIT_DWARF ON CACHE BOOL "")
set(LLVM_TARGETS_TO_BUILD
  X86
  AArch64 CACHE STRING "")
set(CLANG_ENABLE_STATIC_ANALYZER OFF CACHE BOOL "")
set(CLANG_ENABLE_ARCMT OFF CACHE BOOL "")
